/**
 * Hardhat 컴파일 결과에서 ABI와 bytecode를 추출해 frontend/contract.js 로 내보냅니다.
 * 실행: npm run extract-abi
 */
const fs = require("fs");
const path = require("path");

const artifactPath = path.join(
  __dirname,
  "../artifacts/contracts/Voting.sol/Voting.json"
);
const outputPath = path.join(__dirname, "../frontend/contract.js");

const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));

const output = `// Auto-generated by scripts/extract-abi.js — do not edit manually
// Source: contracts/Voting.sol  |  Compiler: solc ${artifact.compilerVersion ?? "0.8.24"}

export const VOTING_ABI = ${JSON.stringify(artifact.abi, null, 2)};

export const VOTING_BYTECODE = "${artifact.bytecode}";
`;

fs.writeFileSync(outputPath, output, "utf8");
console.log("✅ ABI + bytecode extracted → frontend/contract.js");
console.log(`   ABI entries : ${artifact.abi.length}`);
console.log(`   Bytecode    : ${artifact.bytecode.length} chars`);
